/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import("./components/AppBar.vue")["default"]
    AppContainer: typeof import("./components/AppContainer.vue")["default"]
    Auth: typeof import('./components/Auth.vue')['default']
    Cdp: typeof import("./components/Cdp.vue")["default"]
    Chart: typeof import("./components/Chart.vue")["default"]
    ChatArea: typeof import("./components/ChatArea.vue")["default"]
    ChatContainer: typeof import("./components/ChatContainer.vue")["default"]
    ChatHeader: typeof import("./components/ChatHeader.vue")["default"]
    ChatList: typeof import("./components/ChatList.vue")["default"]
    Credits: typeof import("./components/Credits.vue")["default"]
    Dark: typeof import('./components/Dark.vue')['default']
    Drawer: typeof import("./components/Drawer.vue")["default"]
    GithubRepository: typeof import('./components/GithubRepository.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    MessageInput: typeof import("./components/MessageInput.vue")["default"]
    MessageUpload: typeof import("./components/Upload.vue")["default"]
    Modal: typeof import('./components/Modal.vue')['default']
    Monitoring: typeof import("./components/Monitoring.vue")["default"]
    NavBar: typeof import('./components/NavBar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    Pomodoro: typeof import("./components/Pomodoro.vue")["default"]
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchContact: typeof import("./components/SearchContact.vue")["default"]
    SearchRepos: typeof import('./components/SearchRepos.vue')['default']
    ServerEvent: typeof import('./components/ServerEvent.vue')['default']
    SideBar: typeof import("./components/SideBar.vue")["default"]
    Sse: typeof import("./components/ServerEvent.vue")["default"]
    Templates: typeof import('./components/Templates.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
    UserHeader: typeof import("./components/UserHeader.vue")["default"]
    WebSocket: typeof import('./components/WebSocket.vue')['default']
  }
}
