/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    GithubRepository: typeof import('./components/GithubRepository.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchRepos: typeof import('./components/SearchRepos.vue')['default']
    ServerEvent: typeof import('./components/ServerEvent.vue')['default']
    Templates: typeof import('./components/Templates.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
    WebSocket: typeof import('./components/WebSocket.vue')['default']
  }
}
